### ISSUE TITLE
Version of Cameo 18.5

### ISSUE THREAD

**Issue by jaivgar** [IncQueryLabs/arrowhead-tools#11]
Hello,

I wonder which incompatibilities or problems will appear if we use an earlier version of Cameo Systems Modeler, for example 18.5. Have you tried something similar?

**Comment by gkulcsar** [comment]
Hello, sorry for the huge delay - notice that this is a low-effort endeavor within a huge project and it took as some time to clarify workflows and responsibilities.

As to your question, we haven't tested it thoroughly, but generally: it should work, but using the latest version is always recommended.

**Comment by jaivgar** [comment]
Hello, it was partially working, but eventually we updated our version of Cameo to 19.
