### ISSUE TITLE
Role based authorization

### ISSUE THREAD

**Issue by kkadosa** [IncQueryLabs/arrowhead-tools#2]
Currently AHF only supports direct authorization. That just doesn't sound to scale well.

**Comment by kkadosa** [comment]
[This](https://pdfs.semanticscholar.org/15b5/aba68745dada600e031160fdde1b003e5cce.pdf) talks about related elements. They create an extension to model security.

**Comment by kkadosa** [comment]
Many similar papers exist, defining profiles to model security in SysML:
[SysML Models and Model Transformation for Security
](https://www.researchgate.net/publication/298789834_SysML_Models_and_Model_Transformation_for_Security)[Modeling Security Requirements](https://pdfs.semanticscholar.org/c90a/6b74acc34cb66cf0d45bb21ab193756c5ff7.pdf)
[A Model-Based Approach to Security Analysis](https://arxiv.org/pdf/1710.11442.pdf)
[Security-Aware, Model-Based Systems Engineering with SysML ](https://pdfs.semanticscholar.org/15b5/aba68745dada600e031160fdde1b003e5cce.pdf)
[A SysML Extension for Security Analysis of Industrial Control Systems](https://www.researchgate.net/publication/301389195_A_SysML_Extension_for_Security_Analysis_of_Industrial_Control_Systems)
But they focus on automatic, formal verification of security, and to this end they're both complicated
and lack the exact instance-level control we seek.

**Comment by kkadosa** [comment]
OWASP has a [cheat sheet of related issues.](https://cheatsheetseries.owasp.org/cheatsheets/Access_Control_Cheat_Sheet.html)

**Comment by gkulcsar** [comment]
This has been discussed on project level - no change in strategy due to other constraints.
