### ISSUE TITLE
SysML representation of services

### ISSUE THREAD

**Issue by kkadosa** [IncQueryLabs/arrowhead-tools#3]
Services could be represented as blocks and reference properties, or as ports on the systems. There are good cases for both.

**Comment by kkadosa** [comment]
Blocks and associations!

**Comment by gkulcsar** [comment]
Current status:

1) There is a high-level contextual modeling layer, with stereotyped dependencies for provide/consume relations.

2) Planned: Represent connections as SysML Connections (keeping 1) and providing a more concrete representation)

**Comment by kkadosa** [comment]
Introduced double layered (definition - realization) based metamodel, with systems, services and interfaces in completely separate elements, connected with stereotyped dependencies.
